2022-12-19 17:00:07,123 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:01:07 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:01:07,115 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:02:07 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:02:07,110 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:03:07 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:03:53,067 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:04:53 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:04:53,065 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:05:53 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:05:53,057 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:06:53 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:06:53,056 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:07:53 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:07:53,066 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:08:53 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:09:49,774 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:10:49 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:10:49,774 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:11:49 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:11:49,779 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:12:49 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:12:49,774 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:13:49 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:15:26,021 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:16:26 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:18:12,380 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:19:12 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:19:28,216 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:20:28 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:20:28,219 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:21:28 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:21:28,211 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:22:28 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:22:57,390 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:23:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:23:38,923 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:24:38 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:23:57,383 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:24:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:24:38,917 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:25:38 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:24:57,385 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:25:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:25:38,927 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:26:38 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:25:57,385 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:26:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:26:38,926 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:27:38 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:26:57,388 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:27:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:27:38,922 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:28:38 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:27:57,390 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:28:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:28:38,912 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:29:38 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:28:57,385 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:29:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:29:57,376 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:30:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:30:37,904 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:31:37 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:30:57,381 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:31:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:31:37,898 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:32:37 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:31:57,386 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:32:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:32:37,908 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:33:37 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:32:57,385 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:33:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:33:57,382 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:34:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:34:14,539 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:35:14 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:34:57,384 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:35:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:35:14,535 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:36:14 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    customers = Customer.query.all()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:35:57,380 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:36:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:36:57,381 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:37:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:36:57,741 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:37:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 45, in get
    updated_cust = Customer.query.filter_by(id=cust['id']).first()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:37:57,377 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:38:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:37:57,677 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:38:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 41, in get
    em['To'] = recipient
  File "C:\Users\jojo\.pyenv\pyenv-win\versions\3.10.6\lib\email\message.py", line 407, in __setitem__
    raise ValueError("There may be at most {} {} headers "
ValueError: There may be at most 1 To headers in a message
2022-12-19 17:38:57,378 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:39:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:38:57,682 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:39:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 41, in get
    em['To'] = recipient
  File "C:\Users\jojo\.pyenv\pyenv-win\versions\3.10.6\lib\email\message.py", line 407, in __setitem__
    raise ValueError("There may be at most {} {} headers "
ValueError: There may be at most 1 To headers in a message
2022-12-19 17:39:57,378 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:40:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:39:57,683 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:40:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 41, in get
    em['To'] = recipient
  File "C:\Users\jojo\.pyenv\pyenv-win\versions\3.10.6\lib\email\message.py", line 407, in __setitem__
    raise ValueError("There may be at most {} {} headers "
ValueError: There may be at most 1 To headers in a message
2022-12-19 17:40:57,377 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:41:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:40:57,682 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:41:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 41, in get
    em['To'] = recipient
  File "C:\Users\jojo\.pyenv\pyenv-win\versions\3.10.6\lib\email\message.py", line 407, in __setitem__
    raise ValueError("There may be at most {} {} headers "
ValueError: There may be at most 1 To headers in a message
2022-12-19 17:41:57,388 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:42:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:42:57,377 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:43:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:43:57,388 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:44:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:44:57,385 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:45:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:45:57,387 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:46:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:46:57,388 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:47:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:47:57,383 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:48:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:48:57,375 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:49:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:49:57,378 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:50:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:50:57,384 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:51:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:51:57,382 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:52:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:52:57,379 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:53:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:53:57,377 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:54:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:56:57,382 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:57:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:57:57,375 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:58:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:58:16,267 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:59:16 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 88, in get
    updated_cust['status'] = 'Inactive'
TypeError: 'Customer' object does not support item assignment
2022-12-19 17:58:57,385 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 17:59:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 17:59:57,380 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 18:00:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 18:00:57,387 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 18:01:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 18:01:57,388 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 18:02:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 19:19:57,381 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 19:20:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2022-12-19 19:20:57,389 - apscheduler.executors.default - ERROR - Job "RajeshEmailNotif.get (trigger: interval[0:01:00], next run at: 2022-12-19 19:21:57 +07)" raised an exception
Traceback (most recent call last):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\app\resources\rajesh_notif_task.py", line 26, in get
    def get(self):
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\jojo\OneDrive\Email attachments\Dokumen\BackEnd\email-notif\.venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
